version: '3.3'
services:

  ingress:
    container_name: ingress
    image: openresty/openresty:alpine
    working_dir: /workspace
    restart: on-failure
    tty: true 
    ports:      
      - 8080:80    
    volumes:
      - ./conf.d:/etc/nginx/conf.d      
      - ./lib:/workspace/lib
      - ./www:/var/www
    command: tail -f /dev/null
