services:
  ingress:
    container_name: ingress
    build: .
    working_dir: /workspace
    restart: on-failure
    tty: true
    ports:
      - 80:80    
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./lib:/workspace/lib
      - ./www:/var/www
      - ./logs:/var/log/nginx
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - net

networks:
  net:
    name: net
    external: true
